# Use an official Node runtime as a parent image
FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm ci --production

COPY . .

RUN npm run build

EXPOSE 4000
CMD ["npm", "start"]
