version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: multi_tool
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: .
    command: npm run dev
    environment:
      DATABASE_URL: "postgresql://demo:demo@db:5432/multi_tool"
      JWT_SECRET: "replace_me"
    volumes:
      - ./:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db
volumes:
  db_data:
