name: CI

on:
  push:
    branches: [ main, backend/scaffold ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install
        working-directory: backend
        run: npm ci
      - name: Generate Prisma client
        working-directory: backend
        run: npx prisma generate
      - name: Lint
        working-directory: backend
        run: npm run lint
      - name: Build
        working-directory: backend
        run: npm run build
      - name: Test
        working-directory: backend
        run: npm run test
